defmodule ArtNet.Packet.BitField do
  @moduledoc """
  DSL for defining packed bit-field structs.

  `ArtNet.Packet.BitField` maps named struct fields to bit ranges inside a
  single unsigned integer. Packet schemas use bit-field modules with the
  `{:bit_field, Module}` field format.

  ```elixir
  defmodule ArtNet.Packet.BitField.TalkToMe do
    use ArtNet.Packet.BitField

    defbitfield bit_size: 8 do
      field(:reply_on_change, :boolean, offset: 1)
      field(:diagnostics, :boolean)
      field(:diag_unicast, :boolean)
      field(:vlc, :boolean)
    end
  end
  ```

  Fields are packed from the least-significant bit upward. Each field starts at
  the current bit offset unless the `:offset` option is provided, in which case
  that offset is added before placing the field. After a field is placed, the
  current offset advances by the field size.

  A bit-field module generated by `defbitfield/2` receives:

    * `bit_field_schema/0` - returns field formats and bit ranges.
    * `bit_size/0` - returns the total bit size declared for the field.
    * `decode/1` - converts an unsigned integer into the generated struct.
    * `encode/1` - converts the generated struct into an unsigned integer.

  ## Field formats

    * `:boolean` - a one-bit boolean value.
    * `{:enum_table, module}` - an enum value whose size is taken from the
      referenced `ArtNet.Packet.EnumTable` module's `bit_size/0`.
  """

  alias ArtNet.Packet.Schema
  alias ArtNet.Packet.Schema.Docs

  import Bitwise

  @struct_accumulate_attrs [
    :artnet_fields,
    :artnet_enforce_keys,
    :artnet_types,
    :artnet_schema,
    :artnet_field_descriptions
  ]

  @type schema_type :: Schema.bit_field_format()

  @doc false
  defmacro __using__(_) do
    quote do
      import ArtNet.Packet.BitField, only: [defbitfield: 2]
    end
  end

  @doc """
  Defines a packed bit-field schema and generates its typed struct.

  Inside a `defbitfield` block, each field is defined through the `field/3`
  macro.

  ## Options

    * `:bit_size` - required total bit size of the encoded integer.
  """
  defmacro defbitfield(opts, do: block) do
    ArtNet.Packet.BitField.__defbitfield__(opts, block)
  end

  @doc false
  def __defbitfield__(opts, block) do
    quote do
      Enum.each(unquote(@struct_accumulate_attrs), fn attr ->
        Module.register_attribute(__MODULE__, attr, accumulate: true)
      end)

      @artnet_bit_field_offset 0

      import ArtNet.Packet.BitField

      unquote(block)

      @enforce_keys @artnet_enforce_keys
      defstruct Enum.reverse(@artnet_fields)

      ArtNet.Packet.BitField.__struct_type__(@artnet_types)

      @bit_size Keyword.fetch!(unquote(opts), :bit_size)
      @schema Enum.reverse(@artnet_schema)

      moduledoc =
        ArtNet.Packet.BitField.__moduledoc_with_layout__(
          Module.get_attribute(__MODULE__, :moduledoc),
          @bit_size,
          @schema,
          Enum.reverse(@artnet_fields),
          @artnet_enforce_keys,
          Enum.reverse(@artnet_field_descriptions)
        )

      Module.put_attribute(__MODULE__, :moduledoc, {__ENV__.line, moduledoc})

      @doc ArtNet.Packet.BitField.__bit_field_schema_doc__()
      @spec bit_field_schema :: [
              {key :: atom,
               {ArtNet.Packet.BitField.schema_type(),
                {start_bit :: non_neg_integer, length :: pos_integer}}}
            ]
      def bit_field_schema, do: @schema

      @doc ArtNet.Packet.BitField.__bit_size_doc__(@bit_size)
      @spec bit_size :: pos_integer
      def bit_size, do: @bit_size

      @doc """
      Decodes an unsigned integer into this bit-field struct.
      """
      @spec decode(non_neg_integer) :: {:ok, t()} | :error
      def decode(value), do: ArtNet.Packet.BitField.decode(value, __MODULE__)

      @doc """
      Encodes this bit-field struct into an unsigned integer.
      """
      @spec encode(t()) :: {:ok, non_neg_integer} | :error
      def encode(struct), do: ArtNet.Packet.BitField.encode(struct, __MODULE__)
    end
  end

  @doc false
  @spec __moduledoc_with_layout__(
          false | nil | String.t() | {non_neg_integer, String.t()},
          pos_integer,
          [
            {atom, {schema_type(), {start_bit :: non_neg_integer, length :: pos_integer}}}
          ],
          Keyword.t(),
          [atom],
          Keyword.t()
        ) ::
          false | String.t()
  def __moduledoc_with_layout__(false, _bit_size, _schema, _fields, _enforce_keys, _descriptions),
    do: false

  def __moduledoc_with_layout__(moduledoc, bit_size, schema, fields, enforce_keys, descriptions) do
    layout = """
    ## Bit layout

    #{Docs.bit_field_layout_table(schema, fields, enforce_keys, descriptions)}
    """

    moduledoc
    |> Docs.moduledoc_text()
    |> Docs.append_section(bit_size_section(bit_size))
    |> Docs.append_section(layout)
  end

  @doc false
  @spec __bit_size_doc__(pos_integer) :: String.t()
  def __bit_size_doc__(bit_size) do
    """
    Returns the total number of bits encoded by this bit field.

    This bit field is encoded in `#{bit_size}` bits.
    """
  end

  @doc false
  @spec __bit_field_schema_doc__() :: String.t()
  def __bit_field_schema_doc__ do
    """
    Returns the bit-field schema in declaration order.
    """
  end

  defmacro __struct_type__(types) do
    quote bind_quoted: [types: types] do
      @type t() :: %__MODULE__{unquote_splicing(types)}
    end
  end

  @doc """
  Defines a field in a bit-field schema.

  Fields are positioned from the least-significant bit upward. `:boolean`
  fields consume one bit, and `{:enum_table, module}` fields consume the
  referenced enum table's `bit_size/0`.

  ## Options

    * `:default` - default struct value. Without this option, the field is an
      enforced key.
    * `:offset` - number of bits to skip before placing this field.
    * `:description` - field description shown in the generated bit layout
      docs.
  """
  defmacro field(name, format, opts \\ []) do
    quote bind_quoted: [name: name, format: format, opts: opts] do
      ArtNet.Packet.BitField.__field__(name, format, opts, __ENV__)
    end
  end

  @doc false
  def __field__(name, format, opts, env) do
    %Macro.Env{module: module} = env

    unless is_atom(name) do
      raise ArgumentError, "a field name must be an atom, got: #{inspect(name)}"
    end

    if module |> Module.get_attribute(:artnet_fields) |> Keyword.has_key?(name) do
      raise ArgumentError, "the field #{inspect(name)} is already set"
    end

    case Keyword.fetch(opts, :description) do
      {:ok, description} when not is_binary(description) ->
        raise ArgumentError,
              "the description option for field #{inspect(name)} must be a string, got: #{inspect(description)}"

      _ ->
        :ok
    end

    default = Keyword.get(opts, :default)
    has_default? = Keyword.has_key?(opts, :default)
    enforce? = not has_default?

    offset =
      Module.get_attribute(module, :artnet_bit_field_offset) + Keyword.get(opts, :offset, 0)

    size =
      case format do
        :boolean -> 1
        {:enum_table, module} -> module.bit_size()
      end

    Module.put_attribute(module, :artnet_bit_field_offset, offset + size)

    Module.put_attribute(module, :artnet_fields, {name, default})

    Module.put_attribute(
      module,
      :artnet_types,
      {name, ArtNet.Packet.Schema.Types.bit_field_type_for(format)}
    )

    if enforce?, do: Module.put_attribute(module, :artnet_enforce_keys, name)

    Module.put_attribute(module, :artnet_schema, {name, {format, {offset, size}}})

    Module.put_attribute(
      module,
      :artnet_field_descriptions,
      {name, Keyword.get(opts, :description, "")}
    )
  end

  @doc """
  Decodes an unsigned integer into a bit-field struct.

  The `module` must be a module generated with `defbitfield/2`.
  """
  @spec decode(non_neg_integer, module) :: {:ok, struct} | :error
  def decode(value, module) do
    module.bit_field_schema()
    |> Enum.reduce_while({:ok, []}, fn {key, {type, {offset, length}}}, {:ok, acc} ->
      extracted_value = extract_bits(value, offset, length)

      case cast_value(type, extracted_value) do
        {:ok, result} -> {:cont, {:ok, [{key, result} | acc]}}
        :error -> {:halt, :error}
      end
    end)
    |> case do
      {:ok, params} -> {:ok, struct!(module, params)}
      :error -> :error
    end
  end

  @doc """
  Encodes a bit-field struct into an unsigned integer.

  The `module` must be a module generated with `defbitfield/2`.
  """
  @spec encode(struct, module) :: {:ok, non_neg_integer} | :error
  def encode(struct, module) do
    Enum.reduce_while(module.bit_field_schema(), {:ok, 0}, fn {key, {type, {offset, _}}},
                                                              {:ok, acc} ->
      case dump_value(type, Map.fetch!(struct, key)) do
        {:ok, encode_value} -> {:cont, {:ok, acc + (encode_value <<< offset)}}
        :error -> {:halt, :error}
      end
    end)
  end

  @spec cast_value(schema_type(), non_neg_integer) :: {:ok, any} | :error
  defp cast_value(:boolean, 0), do: {:ok, false}
  defp cast_value(:boolean, 1), do: {:ok, true}
  defp cast_value({:enum_table, enum_module}, value), do: enum_module.to_atom(value)

  @spec dump_value(schema_type(), any) :: {:ok, non_neg_integer} | :error
  defp dump_value(:boolean, false), do: {:ok, 0}
  defp dump_value(:boolean, true), do: {:ok, 1}
  defp dump_value({:enum_table, enum_module}, value), do: enum_module.to_code(value)

  defp bit_size_section(bit_size) do
    """
    ## Bit size

    This bit field is encoded in `#{bit_size}` bits.
    """
    |> String.trim_trailing()
  end

  @doc """
  Extracts bits from a value.

  ### Examples

      iex> ArtNet.Packet.BitField.extract_bits(0b0110, 0, 2)
      0b10

      iex> ArtNet.Packet.BitField.extract_bits(0b0110, 2, 2)
      0b01

      iex> ArtNet.Packet.BitField.extract_bits(0b0110, 2, 4)
      0b0001
  """
  @spec extract_bits(integer, non_neg_integer, pos_integer) :: non_neg_integer
  def extract_bits(value, offset, length) do
    mask = (1 <<< length) - 1
    value >>> offset &&& mask
  end
end
