defmodule ArtNet.Packet.EnumTable.AddressCommand do
  @moduledoc """
  Address command values used by `ArtNet.Packet.ArtAddress`.

  These values encode the command byte that changes node state or per-port
  behavior.
  """

  use ArtNet.Packet.EnumTable

  defenumtable([bit_size: 8],
    ac_none: {0x00, description: "No command."},
    ac_cancel_merge: {0x01, description: "Cancel merge mode."},
    ac_led_normal: {0x02, description: "Set indicator LEDs to normal."},
    ac_led_mute: {0x03, description: "Mute indicator LEDs."},
    ac_led_locate: {0x04, description: "Set indicator LEDs to locate."},
    ac_reset_rx_flags: {0x05, description: "Reset receiver status flags."},
    ac_analysis_on: {0x06, description: "Enable analysis mode."},
    ac_analysis_off: {0x07, description: "Disable analysis mode."},
    ac_fail_hold: {0x08, description: "Set failsafe behavior to hold last output."},
    ac_fail_zero: {0x09, description: "Set failsafe behavior to all zero."},
    ac_fail_full: {0x0A, description: "Set failsafe behavior to all full."},
    ac_fail_scene: {0x0B, description: "Set failsafe behavior to playback scene."},
    ac_fail_record: {0x0C, description: "Record the failsafe scene."},
    ac_merge_ltp0: {0x10, description: "Set output port 0 to LTP merge."},
    ac_merge_ltp1: {0x11, description: "Set output port 1 to LTP merge."},
    ac_merge_ltp2: {0x12, description: "Set output port 2 to LTP merge."},
    ac_merge_ltp3: {0x13, description: "Set output port 3 to LTP merge."},
    ac_direction_tx0: {0x20, description: "Set port 0 to output."},
    ac_direction_tx1: {0x21, description: "Set port 1 to output."},
    ac_direction_tx2: {0x22, description: "Set port 2 to output."},
    ac_direction_tx3: {0x23, description: "Set port 3 to output."},
    ac_direction_rx0: {0x30, description: "Set port 0 to input."},
    ac_direction_rx1: {0x31, description: "Set port 1 to input."},
    ac_direction_rx2: {0x32, description: "Set port 2 to input."},
    ac_direction_rx3: {0x33, description: "Set port 3 to input."},
    ac_merge_htp0: {0x50, description: "Set output port 0 to HTP merge."},
    ac_merge_htp1: {0x51, description: "Set output port 1 to HTP merge."},
    ac_merge_htp2: {0x52, description: "Set output port 2 to HTP merge."},
    ac_merge_htp3: {0x53, description: "Set output port 3 to HTP merge."},
    ac_art_net_sel0: {0x60, description: "Select Art-Net input for port 0."},
    ac_art_net_sel1: {0x61, description: "Select Art-Net input for port 1."},
    ac_art_net_sel2: {0x62, description: "Select Art-Net input for port 2."},
    ac_art_net_sel3: {0x63, description: "Select Art-Net input for port 3."},
    ac_acn_sel0: {0x70, description: "Select sACN input for port 0."},
    ac_acn_sel1: {0x71, description: "Select sACN input for port 1."},
    ac_acn_sel2: {0x72, description: "Select sACN input for port 2."},
    ac_acn_sel3: {0x73, description: "Select sACN input for port 3."},
    ac_clear_op0: {0x90, description: "Clear output state for port 0."},
    ac_clear_op1: {0x91, description: "Clear output state for port 1."},
    ac_clear_op2: {0x92, description: "Clear output state for port 2."},
    ac_clear_op3: {0x93, description: "Clear output state for port 3."},
    ac_style_delta0: {0xA0, description: "Select delta output style for port 0."},
    ac_style_delta1: {0xA1, description: "Select delta output style for port 1."},
    ac_style_delta2: {0xA2, description: "Select delta output style for port 2."},
    ac_style_delta3: {0xA3, description: "Select delta output style for port 3."},
    ac_style_const0: {0xB0, description: "Select constant output style for port 0."},
    ac_style_const1: {0xB1, description: "Select constant output style for port 1."},
    ac_style_const2: {0xB2, description: "Select constant output style for port 2."},
    ac_style_const3: {0xB3, description: "Select constant output style for port 3."},
    ac_rdm_enable0: {0xC0, description: "Enable RDM on port 0."},
    ac_rdm_enable1: {0xC1, description: "Enable RDM on port 1."},
    ac_rdm_enable2: {0xC2, description: "Enable RDM on port 2."},
    ac_rdm_enable3: {0xC3, description: "Enable RDM on port 3."},
    ac_rdm_disable0: {0xD0, description: "Disable RDM on port 0."},
    ac_rdm_disable1: {0xD1, description: "Disable RDM on port 1."},
    ac_rdm_disable2: {0xD2, description: "Disable RDM on port 2."},
    ac_rdm_disable3: {0xD3, description: "Disable RDM on port 3."},
    ac_bqp0: {0xE0, description: "Configure the BQP value to 0."},
    ac_bqp1: {0xE1, description: "Configure the BQP value to 1."},
    ac_bqp2: {0xE2, description: "Configure the BQP value to 2."},
    ac_bqp3: {0xE3, description: "Configure the BQP value to 3."},
    ac_bqp4: {0xE4, description: "Configure the BQP value to 4."},
    ac_bqp5: {0xE5, description: "Configure the BQP value to 5."},
    ac_bqp6: {0xE6, description: "Configure the BQP value to 6."},
    ac_bqp7: {0xE7, description: "Configure the BQP value to 7."},
    ac_bqp8: {0xE8, description: "Configure the BQP value to 8."},
    ac_bqp9: {0xE9, description: "Configure the BQP value to 9."},
    ac_bqp10: {0xEA, description: "Configure the BQP value to 10."},
    ac_bqp11: {0xEB, description: "Configure the BQP value to 11."},
    ac_bqp12: {0xEC, description: "Configure the BQP value to 12."},
    ac_bqp13: {0xED, description: "Configure the BQP value to 13."},
    ac_bqp14: {0xEE, description: "Configure the BQP value to 14."},
    ac_bqp15: {0xEF, description: "Configure the BQP value to 15."}
  )
end
